### ISSUE TITLE
Problems with installing ond different OS´s

### ISSUE THREAD

**Issue by AmmonStretz** [uwdata/errudite#8]
2 other students and me tried to install errudite and had the problem,
that it breaks in while installing allennlp==0.8.4
This is the error:
```
ERROR: Could not find a version that satisfies the requirement torch>=0.4.1 (from allennlp==0.8.4) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=0.4.1 (from allennlp==0.8.4)
```

And before that there was an error after the pip install --editable.
But it does not break everything.
`ERROR: spacy 2.1.3 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.1.1 which is incompatible.`

I did everythin inside of Windows10 and also on a linux
Do you have any idea?

Oh I forgott, here are my instalation steps.

git clone https://github.com/uwdata/errudite
cd errudite
virtualenv --no-site-packages -p "C:\Users\ ... \Python36\python.exe" venv
call venv\Scripts\activate
pip install --editable .
mkdir caches
python -m errudite.download --cache_folder_name squad-10570 --cache_path ./caches/
pip install allennlp==0.8.4

**Comment by tongshuangwu** [comment]
Sorry for my late reply!

> ERROR: Could not find a version that satisfies the requirement torch>=0.4.1 (from allennlp==0.8.4) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=0.4.1 (from allennlp==0.8.4)

I re-ran the installation steps on my end and looks like it works fine at least on my macOS. I will try a linux machine tomorrow, but for now my guess is it might have to do with the pytorch distribution on different OS systems. In the `Allennlp` instruction page, they mentioned: "_pip currently installs Pytorch for CUDA 9 only (or no GPU). If you require an older version, please visit https://pytorch.org/ and install the relevant pytorch binary._"
 
If the only thing broken is the `Allennlp` installation (it's a standalone NLP research library that's only used in the ui demo), you can consider following their official instruction here? https://github.com/allenai/allennlp 
I've checked and their latest version (i.e., `allennlp==0.9.0`) should be compatible with the ui. 

> ERROR: spacy 2.1.3 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.1.1 which is incompatible.

This is a known problem with some of the dependencies having conflicts with each other, but like you have seen, it doesn't break other things, so it's safe to leave it there!

I will report back if I find additional steps needed on Linux, let me know if you make it work before that :)

**Comment by tongshuangwu** [comment]
Following up on this, I tried the installation on a Windows machine:

- If you use WSL (windows subsystem for linux), then `pip install allennlp==0.8.4` or `pip install allennlp==0.9.0` should work perfectly fine. I tested it on a `Ubuntu 18.04.2 LTS` WSL.
- If you use the natural windows system, because of the pytorch distribution difference, you will want to first install pytorch separately before you install allennlp:
```sh
# (reference: https://github.com/allenai/allennlp, https://pytorch.org/)
pip install torch==1.3.0+cpu torchvision==0.4.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
pip install allennlp
```

Let me know if it fixes your issue!

**Comment by AmmonStretz** [comment]
Thank you so mutch. It is running.
The last Step you Comment you wrote fixed the Problem.
At the moment one of us has the mysql problem you mentioned but
if I can reproduce these steps on a docker image that should not be a problem anymore
and everyone can use it.
