### ISSUE TITLE
Unable to reproduce SPACE DASH SPACE example from demo

### ISSUE THREAD

**Issue by knuser** [uwdata/errudite#9]
Hi,

Thanks for wonderful work. I'm trying to reproduce demo steps in GUI and stuck on example about rewriting dash rules: https://youtu.be/Dil5i0AYyu8?t=188

As you can see only one example is found and no spaces are added:
![Screenshot from 2019-11-14 13-24-49](https://user-images.githubusercontent.com/51361990/68857058-477d7000-06e2-11ea-8bf9-7926f854ce97.png)

Is this a bug or am I doing something wrong?

**Comment by knuser** [comment]
Also during installation of `requirements.txt` in **fresh** virtual env I see a version conflict:
`ERROR: spacy 2.1.3 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.1.1 which is incompatible.`

After reinstalling spacy (`pip install spacy==2.1.3`) to fix jsonschema version conflict and installing `tutorials/requirements_tutorial.txt` i see again conflict:

`ERROR: jupyterlab-server 0.3.4 has requirement jsonschema>=3.0.1, but you'll have jsonschema 2.6.0 which is incompatible.`

**Comment by tongshuangwu** [comment]
> As you can see only one example is found and no spaces are added:

Thanks for reporting this! I quickly checked, and turned out it's a bug I introduced during refactoring. Could you please pull from the master branch, and see if it's working now?

> ERROR: spacy 2.1.3 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.1.1 which is incompatible.

This is a known problem with some of the dependencies having conflicts with each other, but like you have seen, it doesn't break other things, so it's safe to leave it there!

**Comment by knuser** [comment]
> Could you please pull from the master branch, and see if it's working now?

It is working now on `incorrect_preprocessing` group. Thank you.


I tried also applying dash separation on `all_instances`, after fresh server start (no other data groups or rewrite rules were present) and saw that hint below text is sometimes incorrect:
![Screenshot from 2019-11-15 11-36-00](https://user-images.githubusercontent.com/51361990/68937681-1d3cb880-079d-11ea-945e-54ff7e6a8457.png)

**Comment by tongshuangwu** [comment]
Sorry for my late reply! I was overwhelmed by some other projects.
Could you please elaborate what's the issue? From the figure, I didn't see anything abnormal?

**Comment by knuser** [comment]
Hi, sure:
![Screenshot (1)](https://user-images.githubusercontent.com/51361990/70607976-ab228c80-1bff-11ea-8822-4ffa6ba8378d.png)

**Comment by tongshuangwu** [comment]
I see. I'm guessing your question is, "why the inline edit does not match with the blue predictions?" Sorry if it's confusing, but this is not a bug :)

In the command, what we are requesting is to replace "-" with " - " in _the sentence that contains the groundtruth_ -- not the _groundtruth span_. Like in the first example:
- The groundtruth (and the prediction, judging by the blue color indicating correct prediction) is "South Pacific"
- "South Pacific" is in the first sentence of the context
- In this sentence (not the groundtruth span), there is one "-" in 1883-84
- Errudite edits it, hence the _inline edit status_ shows "~1883-84~" -> "1883 - 84". 
- The span "South Pacific" is not affected by the edit, and after the edit, the model prediction is still this span, hence the _prediction delta status_ shows "South Pacific" -> "South Pacific".

The core idea is, editing the groundtruth sentence does not necessarily affect the model prediction, and these two examples in the screenshot happen to be un-affected.

In `incorrect_preprocessing`, we required the prediction span to be close to the groundtruth span (hence usually in the same sentence) and to have "-". In other words, whenever you modify `"-" -> " - "`, you are modifying the prediction span, and hence the inline edit can be matched with the blue/orange prediction status.

Does this make sense?

**Comment by knuser** [comment]
Oh, now I get it. Thanks for clear explanation, it makes perfect sense.

Thank you
